### PR TITLE
feat CRUD for quotation

### PR DESCRIPTION
**Pull request by reddhilario**
ticket link: https://app.clickup.com/t/865bk5xb6

added create for quotation

### CODE REVIEW

**Comment by reddhilario** [comment]
Task linked: [CU-865bk5xb6 Store Quotation in DB](https://app.clickup.com/t/865bk5xb6)

**Comment by ezekielreginio** [comment]
Task linked: [CU-865bk5xce Get a Quotation by ID](https://app.clickup.com/t/865bk5xce)

**Comment by ezekielreginio** [comment]
Task linked: [CU-865bk5xbp Update Quotation in DB](https://app.clickup.com/t/865bk5xbp)

**Comment by ezekielreginio** [comment]
Task linked: [CU-865bk5xc0 Soft Delete a Quotation in DB](https://app.clickup.com/t/865bk5xc0)

**Review by ezekielreginio — APPROVED** [review]

**Pull request merged**
